### ISSUE TITLE
编译时报了以下错误，是什么原因导致的?

### ISSUE THREAD

**Issue by hyl87** [biezhihua/FFmpegBuildTool#1]
expr: warning: unportable BRE: `^\\([^\\-].*\\)$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\(--[^=]*\\)=.*$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^--[^=]*=\\(.*\\)$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\([^\\-].*\\)$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\(--[^=]*\\)=.*$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^--[^=]*=\\(.*\\)$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\([^\\-].*\\)$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^\\(--[^=]*\\)=.*$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
expr: warning: unportable BRE: `^--[^=]*=\\(.*\\)$': using `^' as the first character
of the basic regular expression is not portable; it is being ignored
Auto-config: --arch=arm
ERROR: Failed to create toolchain.
touch: cannot touch `/c/Android/workspace/FFmpegBuildTool/android/build/ffmpeg-armv7a/toolchain/touch': No such file or directory

**Comment by hyl87** [comment]
ffmpeg 的版本是4.1

**Comment by biezhihua** [comment]
@hyl87 你的编译环境是什么？

**Comment by hyl87** [comment]
@biezhihua win10

**Comment by biezhihua** [comment]
由于我没有Windows电脑，Windows系统我目前还没有兼容过。

不过我这个脚本是从IJKPlayer上借鉴来的，你可以参考这个文件：
https://github.com/Bilibili/ijkplayer/blob/master/android/contrib/compile-ffmpeg.sh

https://github.com/Bilibili/ijkplayer/blob/master/android/contrib/tools/do-detect-env.sh

其中有两段和CYGWIN相关的脚本：

```
case "$UNAME_S" in
    Darwin)
        export IJK_MAKE_FLAG=-j`sysctl -n machdep.cpu.thread_count`
    ;;
    CYGWIN_NT-*)
        IJK_WIN_TEMP="$(cygpath -am /tmp)"
        export TEMPDIR=$IJK_WIN_TEMP/

        echo "Cygwin temp prefix=$IJK_WIN_TEMP/"
    ;;
esac

```
```
case "$UNAME_S" in
    CYGWIN_NT-*)
        FF_SYSROOT="$(cygpath -am $FF_SYSROOT)"
        FF_PREFIX="$(cygpath -am $FF_PREFIX)"
    ;;
esac
```
自行添加测试。 如果可以正常运行，也欢迎提交PR来支持本项目。
