### ISSUE TITLE
./android/do-compile-android-ffmpeg.sh: line 410: arm-linux-androideabi-clang: command not found

### ISSUE THREAD

**Issue by songzhouzhangSeeNet** [biezhihua/FFmpegBuildTool#11]
Use Compiler: arm-linux-androideabi-clang

./android/do-compile-android-ffmpeg.sh: line 410: arm-linux-androideabi-clang: command not found

Windows 平台下编译
NDK的版本试过了r15、19都不行

**Comment by biezhihua** [comment]
@songzhouzhangSeeNet 由于没有window PC，所以目前没有适配Window版本。

欢迎提交PR。

**Comment by biezhihua** [comment]
https://github.com/biezhihua/FFmpegBuildTool/issues/1

**Comment by Zhangsongsong** [comment]
Ubuntu 系统也是一样的问题

**Comment by Zhangsongsong** [comment]
@biezhihua

**Comment by biezhihua** [comment]
@Zhangsongsong 我抽时间搞个ubuntu虚拟机来兼容一下。

**Comment by biezhihua** [comment]
@songzhouzhangSeeNet @Zhangsongsong @FilenkovMaxim 

麻烦把该问题的全量LOG贴一下。

**Comment by biezhihua** [comment]
@songzhouzhangSeeNet @Zhangsongsong @FilenkovMaxim 

我排查了一下，初步问题是没有安装python导致的。 你们在自己环境中装一下python试试。
