### ISSUE TITLE
Not work on my Mac, while my linux worked

### ISSUE THREAD

**Issue by gmyboy** [biezhihua/FFmpegBuildTool#15]
I have download the newest ffmpeg and openssl, then add ffmpeg-armv7a 、openssl-armv7a to dir **android** manually on my Mac(NDK19).  after that, run:
```
./init-config-ffmpeg.sh lite
./compile-android-openssl.sh armv7a
```
everything work(libssl.a is in the dir : /build/openssl-armv7a/output/lib),but when :
```
./compile-android-ffmpeg.sh armv7a
```
it goes error , nothing *.so generate in dir : /build/ffmpeg-armv7a/output/lib : 
```
ERROR: openssl not found
```
The same operation on my ubuntu(NDK19)  work well .

ffmpeg ffbuild [config.log](https://github.com/biezhihua/FFmpegBuildTool/files/3268429/config.log)

Thx .

**Comment by biezhihua** [comment]
This bug is due to compatibility issues between FFmpeg and Openssl.

You can refer to this for details:` https://patchwork.ffmpeg.org/patch/400/`

I have fixed this error. Please pull the lastest master branch code and recompile it. [commit](https://github.com/biezhihua/FFmpegBuildTool/commit/d26354cd45226281bb97124ca42653a11e09ed6f)

Looking forward to you reply.

**Comment by biezhihua** [comment]
@gmyboy

**Comment by gmyboy** [comment]
I added your patch file, and added below to do-compile-android-ffmpeg.sh:
```
# path configure openssl
# git add -A
# git stash
patch -p0 ./configure ${FF_BUILD_ROOT}/patch/configure-patch.patch
```
The same bug occurred
```
patching file ./configure
ERROR: openssl not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

```
Maybe not the compatibility between those two, 
because it works well without your patch on My Linux

[config.log](https://github.com/biezhihua/FFmpegBuildTool/files/3269645/config.log)

**Comment by biezhihua** [comment]
I‘ve reproduce this bug on my Mac, and I'm sure it caused the error - the patch file.
Instead of manually add the patch file to you project,  stash your code,  pull master code from remote, and rebuild it.

**Comment by biezhihua** [comment]
@gmyboy

**Comment by gmyboy** [comment]
After **git fetch** the newest version of ffmpeg and openssl、rebuild it with that patch file，
Now the compilation is successful. 
But why the patch file not work at first time? Is it because the **./configure** file is not the raw file from git?
Anyway, thanks for your help!!!

PS: U miss **c** in [do-compile-android-ffmpeg.sh](https://github.com/biezhihua/FFmpegBuildTool/commit/d26354cd45226281bb97124ca42653a11e09ed6f#diff-3da064ee848f19dd0c026cd7b46f9008)

**Comment by biezhihua** [comment]
The first time it didn't work because you didn't download the [patch file](https://github.com/biezhihua/FFmpegBuildTool/blob/master/android/patch/configure-patch.patch) locally. 
@gmyboy
