### ISSUE TITLE
Help to integrate with ijkplayer

### ISSUE THREAD

**Issue by rfoa** [biezhihua/FFmpegBuildTool#19]
I found your repository in https://github.com/bilibili/ijkplayer/issues/4558

I was able to compile FFMPEG libs by following the instructions in `README_FFMPEG.md` but I can't integrate with ijkplayer.
I copied the directories and files generated in `/product` and pasted in `/ijkplayer/android/contrib/build/` but it didn't work. The script `/ijkplayer/android/compile-ijk.sh` don't run.

Do you have any tip? Could you please help me?
Thanks!

**Comment by biezhihua** [comment]
I'm sorry, but I'm afraid you can't integrate so files directly with ijkplayer.

Ijkplayer is an excellent player, but it changes too much of the ffmpeg source code.

My compilation script is based on the latest ffmpeg version.

If you are willing to try, you can modify the init-ffmpeg.sh script to modify the ffmpeg repository source for the ijkplayer ffmpeg repository.

Please note that I have not tried this before, and I am not sure if it will succeed.

**Comment by biezhihua** [comment]
https://github.com/bilibili/ijkplayer/blob/master/init-android.sh

https://github.com/biezhihua/FFmpegBuildTool/blob/master/android/init-ffmpeg.sh

change script
```
UPSTREAM=https://github.com/FFmpeg/FFmpeg.git
BRANCH=n4.2
```
to
```
UPSTREAM=https://github.com/Bilibili/FFmpeg.git
BRANCH=ff3.4--ijk0.8.7--20180103--001
```
