### ISSUE TITLE
在windows的sublinux子系统下，输出的结果都是空

### ISSUE THREAD

**Issue by bs111** [biezhihua/FFmpegBuildTool#20]
在window10的linux子系统下执行编译的时候会报错（openssl 和ffmpeg编译都没有结果）:
--------------------
[*] check ffmpeg env
--------------------
./tools/do-compile-ffmpeg.sh: 295: export: Files/Docker/Docker/Resources/bin:/mnt/d/Python37/Scripts:/mnt/d/Python37:/mnt/d/PERL64/SITE/BIN:/mnt/d/PERL64/BIN:/mnt/d/PROGRAM: bad variable name
--------------------
[*] Finished
我的确是在d盘python37下面有windows的python.

![捕获](https://user-images.githubusercontent.com/38519076/66998119-43235e80-f106-11e9-95d5-272490284e0a.PNG)

另外：
初始化FFmpeg配置模块：中的default模式是相对于
https://blog.csdn.net/biezhihua/article/details/86186420 
这个文档中的all配置吗？
          如果你需要更多的编码和格式
         ./init-config-ffmpeg all

环境：
win10 1903 with kali subliunx.

**Comment by biezhihua** [comment]
@bs111 嗨，目前工具还不支持Window版本，并没有为此做适配。

当前工具仅支持Mac和Ubuntu系统，主要是我没有window系统。

如果需要支持Window版本，可以邀请一些人来进行支持。

我会根据实际情况来决定是否对Widnow版本进行支持。

当然，我也非常欢迎您直接提PR来进行支持。
