### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by xiedeacc** [biezhihua/FFmpegBuildTool#21]
rt

**Comment by xiedeacc** [comment]
make_android_product，执行这个函数的patch -p0 ./configure ${current_path}/patch/configure-patch.patch这句话时，出错，提示找不到openssl

**Comment by biezhihua** [comment]
@xiedeacc 晚点我看看

**Comment by taoliuh** [comment]
遇到了同样的问题了。

**Comment by hea0ven** [comment]
> 遇到了同样的问题了。

提示什么呢，我用ndk20.1编译成功了

**Comment by heaoven** [comment]
> rt
@biezhihua  @taoliuh
openssl 补丁打错了，需要打到enabled openssl中
![image](https://user-images.githubusercontent.com/3815071/72059106-53fdfd80-330c-11ea-9fd3-f166729f79e6.png)
修改  
#with openssl
    if [[ -f "${output_path_depend}/lib/libssl.a" ]]; then
        echo "Openssl detected"
        # export pkg_config_path=${output_path_depend}/lib/pkgconfig
        cfg_flags="$cfg_flags --enable-openssl"
        # cfg_flags="$cfg_flags --pkg-config=pkg-config"
        c_flags="$c_flags -I${output_path_depend}/include"
       DEP_LIBS ="$DEP_LIBS -L${output_path_depend}/lib -lssl -lcrypto"
    fi
为:
  if [[ -f "${output_path_depend}/lib/libssl.a" ]]; then
        echo "Openssl detected"
        # export pkg_config_path=${output_path_depend}/lib/pkgconfig
        cfg_flags="$cfg_flags --enable-openssl"
        # cfg_flags="$cfg_flags --pkg-config=pkg-config"
        c_flags="$c_flags -I${output_path_depend}/include"
        ld_libs="$ld_libs -L${output_path_depend}/lib -lssl -lcrypto"
    fi

修改完之后就可以正常编译了

**Comment by biezhihua** [comment]
@taoliuh @hea0ven @FilenkovMaxim 

用最新版本的试试：https://github.com/biezhihua/libs-build-tool 

在master分支，我修改了很多。最后的产物改成了静态库，不再是合并的动态so文件。

此外，目前还不支持动态配置ffmpeg的选项，这块我后续会再改造。

```
# 1
./android.sh --lib-openssl  --arch-armeabi-v7a

# 2
./android.sh --lib-ffmpeg --with-openssl --arch-armeabi-v7a

```
