### ISSUE TITLE
Compile wrong

### ISSUE THREAD

**Issue by toantk238** [biezhihua/FFmpegBuildTool#22]
I see the wrong code here.

Revision : 0d8235753
File : contrib/src/ffmpeg/rules/Makefile Line 178
`F	FMPEGCONF +=  --disable-mmx --disable-mmxext --disable-inline-asm`

Should we remove the char "F" in the beginning ?

**Comment by biezhihua** [comment]
@toantk238 

Yes. This "F" is a typo and I have removed it in a new commit.

Thanks.

[commit](https://github.com/biezhihua/libs-build-tool/commit/cecd5b516d869b7954f406fa60dc8dbda2eef6a1)
