### ISSUE TITLE
Unknown option error

### ISSUE THREAD

**Issue by RajivKulkarni707** [biezhihua/FFmpegBuildTool#23]
Hello,
I am using cygwin on Windows 10 machine and have Android Studio installed.

Copied your repository .

cd ~/libs-build-tool

export ANDROID_HOME=/cygdrive/C/Users/kulka/AppData/Local/Android/Sdk

Then ran following command:->

$ ./android.sh --lib-ffmpeg --ffmpeg-config-min --arch-armeabi-v7a

INFO: Unknown option "".
See ./android.sh --help for available options.

When I checked the code, looks like --lib option is not being handled in ./android/main.sh file.

Any help will be appreciated.

Thanks
Rajiv

**Comment by biezhihua** [comment]
Hello, currently does not support windows platform, I suggest you use ubuntu container under docker to compile.

@RajivKulkarni707
