### ISSUE TITLE
Always INFO: Unknown option "".

### ISSUE THREAD

**Issue by e1001925** [biezhihua/FFmpegBuildTool#25]

**Comment by HancockY** [comment]
same:
INFO: Unknown option "".

**Comment by biezhihua** [comment]
@HancockY @e1001925 

Please upload the log

**Comment by biezhihua** [comment]
There is something wrong with the README, I have updated it

@HancockY @e1001925

**Comment by HancockY** [comment]
> There is something wrong with the README, I have updated it
> 
> @HancockY @e1001925

/Users/hancock/Desktop/libs-build-tool/common/common.sh: line 63: /Users/hancock/Desktop/libs-build-tool/env_tools/init.sh: No such file or directory

when i use "./android.sh --enable-openssl --arch-arm64-v8a"

**Comment by biezhihua** [comment]
> > There is something wrong with the README, I have updated it
> > @HancockY @e1001925
> 
> /Users/hancock/Desktop/libs-build-tool/common/common.sh: line 63: /Users/hancock/Desktop/libs-build-tool/env_tools/init.sh: No such file or directory
> 
> when i use "./android.sh --enable-openssl --arch-arm64-v8a"

Sorry, I accidentally deleted the env_tools directory, you update it to the latest code.
