### ISSUE TITLE
init-config.sh defaule  这个设置会有很多编译错误

### ISSUE THREAD

**Issue by zn123** [biezhihua/FFmpegBuildTool#3]
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function filter_frame: error: undefined reference to 'av_rdft_calc'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'ff_log2_tab'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'av_malloc'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'av_malloc'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'av_rdft_end'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'av_rdft_end'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'av_rdft_init'
libavfilter/af_atempo.o:libavfilter/af_atempo.c:function config_props: error: undefined reference to 'av_rdft_init'
。。。。

**Comment by biezhihua** [comment]
我看下 @zn123

**Comment by biezhihua** [comment]
@zn123 你是什么环境跑的？

我本地跑了下，default 能够正常编译出来。
