### ISSUE TITLE
Is this library support 64 bit

### ISSUE THREAD

**Issue by rameshvoltella** [biezhihua/FFmpegBuildTool#6]
Hi 
This is just a query

As per the new android playstore policy we need to make the native code support 64 bit. is this library support 64 bit?

**Comment by biezhihua** [comment]
@rameshvoltella 

Yes, The library is support 64 bit. e.g: armeabi-v7a / arm64-v8a  x86 / x86_64

But, It not support mips & mips64 ARCH.
