### ISSUE TITLE
如何使用ndk18编译x264

### ISSUE THREAD

**Issue by taoliuh** [biezhihua/FFmpegBuildTool#7]
ndk18 去掉了gcc, 如何在shell脚本里指定clang. 需要如何配置，麻烦您指点一下。

**Comment by biezhihua** [comment]
@taoliuh 目前脚本中默认就是使用clang进行编译的。 不能满足你的需求么？

**Comment by taoliuh** [comment]
@biezhihua 我还想用ndk18编一个x264库，不知道里头的细节，比如如何脚本指定clang及相关的配置。烦请指导下。

**Comment by biezhihua** [comment]
https://developer.android.com/ndk/guides/standalone_toolchain#%E4%BD%BF%E7%94%A8_clang

好多资料都没有记录，你只能自己多搜索一下了。

@taoliuh
