### ISSUE TITLE
用CMakeList组织

### ISSUE THREAD

**Issue by oncealong** [biezhihua/FFmpegBuildTool#8]
看着和ijkplayer的那一套编译差不多的. 有考虑过用CMakeList组织么? 这样更方便源码引入FFmpeg到现有项目中?

**Comment by biezhihua** [comment]
@oncealong 
基础的思路是从ijkplayer借鉴而来的，当然适配多个NDK也踩了不少坑。

另外，你说的使用CMakeList来组织，方便源码项目引入FFmpeg，指的是CMakeList组织编译脚本，将打出来的include和lib直接引入到源码项目中么？ 这样确实会更自动化一些。

**Comment by oncealong** [comment]
适配多NDK确实有很多坑, 尤其是openssl的ndk编译. 辛苦!!!
Android Studio现在默认用CMakeList管理C/C++代码, 为了能更贴合Android Studio, 用上Android Studio的debug特性, 所以想着把FFmpeg也用CMakeList管理, 这样修改后直接运行Android Studio就好, 不用先执行编译脚本, 编译出so. 而且这样debug也会更方便. 现在我都是用XCode调试, 没问题后再用Android Studio跑, 挺麻烦的.

**Comment by biezhihua** [comment]
@oncealong 你的意思是，直接将FFmpeg源码引入到项目中，用CMakeList管理起来，达到可以直接Debug源码的程度？

**Comment by oncealong** [comment]
是这个意思. 不仅是debug, 修改后的编译也比较方便. 对于生成耗时, 可以通过变量控制, "so存在且不重新生成", 则使用已有, 否则就编译.

**Comment by biezhihua** [comment]
@oncealong 你这个想法很好，我也很有兴趣，奈何最近工作很忙， 只能先Delay一下了。

**Comment by oncealong** [comment]
@biezhihua 了解, 我也一直在这样尝试, 有进展交流一下. 这个issue的目的达到了, 所以就先关了.

**Comment by biezhihua** [comment]
@oncealong 方便留个微信么？  讨论下直接引入ffmpeg库的问题。

**Comment by oncealong** [comment]
不好意思, 才看到, 已发邮箱.
