### ISSUE TITLE
代码来自于ijkplayer?

### ISSUE THREAD

**Issue by quqiuzhu** [biezhihua/FFmpegBuildTool#9]
我看代码很像从[ijkplayer](https://github.com/bilibili/ijkplayer)里面抽取出来的， 如果是的话最好注明一下来源和license。

**Comment by biezhihua** [comment]
如果是完全从其中抽出来不加改动，我自然会加上来源和license的。

结构和部分代码思想确实有参考，但是内容是不一致的。 

这个工具并不是在ijkplayer的基础之上做的封装，而是完全改造后发出来的。

**Comment by biezhihua** [comment]
有借鉴吧，但并不是简单抽取。

最核心的NDK16以后的Support，IJKPlayer是不支持的。 要不然我也不会费劲写这个。

**Comment by biezhihua** [comment]
https://github.com/biezhihua/FFmpegBuildTool/blob/master/README.md

这是更新后的Readme

**Comment by biezhihua** [comment]
https://github.com/biezhihua/FFmpegBuildTool/issues/8
